### ISSUE TITLE
Crashing when using NEI

### ISSUE THREAD

**Issue by CassidySlayin** [Sedecias/LexRex#11]
**Game Name:** CassidySlayin
(What game is this bug in?)
keep crashing when trying to into NEI options to change my game from cheat mode to recipe mode
**Project Name:** LexRex MC
(Which Project is this for?)
(e.g. "LexRex MC","The World is Re-Released","Unions Unbridled")

**Brief Description:**
(Short description here.)
I keep crashing everytime I try to change my options settings for NEI in a crafting table or chest inv or just regular inventory
**Reproduction Steps:**
1. (However many steps necessary for us to reproduce the bugs ourselves in a test environment.)
2. (If you encounter the bug fleetingly, and cannot reproduce it, your ticket is likely to be closed.)
3. (You may choose to file it anyway, and we encourage that, but don't be surprised if it lacks progress.)
go into the crafting table, and then hit options for nei, then it should crash
**Additional Information:**
(Additional information, if you have any.)

**Applicable Logs:**
(Please include any logs applicable to your bug.)
(You can create a raw paste on gist.github.com)
[crash-2018-10-16_15.28.48-client.txt](https://github.com/Sedecias/LexRex/files/2484835/crash-2018-10-16_15.28.48-client.txt)

**Alternative Contact:**
(Discord information, steam information, any other >>non-identifying<< method.)

**Comment by Sedecias** [comment]
Staff are unable to reproduce this issue. 
The steps used were:
1. Open inventory with NEI
2. Hit options for NEI
3. Crash
