### ISSUE TITLE
Frostbite bug

### ISSUE THREAD

**Issue by thecrazy13** [Sedecias/LexRex#5]
**Game Name:**
Minecraft

**Project Name:**
LexRex
**Brief Description:**
Frostbite effects will continue after death

**Reproduction Steps:**
1. Acquire frostbite
2. die

**Alternative Contact:**
Discord: thecrazy13#9190

**Comment by Sedecias** [comment]
Seems to have been resolved after disabling temperature effects in entirety for unrelated reasons.
