### ISSUE TITLE
Taint Poison bug

### ISSUE THREAD

**Issue by thecrazy13** [Sedecias/LexRex#6]
**Game Name:**
Minecraft

**Project Name:**
LexRex
**Brief Description:**
Taint poison effect persistent

**Reproduction Steps:**
unknown, was fighting a skeleton and zombies and was suddenly given the effect when hit by them, it then persisted

**Alternative Contact:**
thecrazy13#9190

**Comment by Sedecias** [comment]
Seems to have been resolved after disabling temperature effects in entirety for unrelated reasons.
